/**
 * EventLog — the canonical shape of an activity-stream entry in the
 * BidWorkspace "timeline" sidebar. Right now the sidebar is fed from
 * a static mock; this file defines the contract so we can swap the
 * mock for a real fetch without rewriting the UI.
 *
 * Type additions:
 *   - actor: { id, name, avatarUrl, role } — who did it (helps the
 *     sidebar render real "张经理 approved" vs "system approved").
 *   - meta is intentionally `Record<string, unknown>` because every
 *     event kind has different metadata (rejection events carry a
 *     reason, upload events carry a material id, etc.). UI code
 *     should never index into meta directly — it should switch on
 *     `kind` and use a per-kind metadata view component.
 *
 * Implementation note: EventLogSource is an async-returning
 * interface. The default source is the LocalMockEventLogSource that
 * fans out to workspace-helpers' mock array, so zero code change is
 * needed to go live today. When the backend lands the
 * `/bids/:id/events` endpoint, swap in HttpEventLogSource (not yet
 * implemented) and the UI keeps working.
 */

export type EventKind =
  | 'created'        // bid created
  | 'submitted'      // submitted for review
  | 'approved'       // approved (chapter or whole bid)
  | 'rejected'       // rejected
  | 'regenerated'    // chapter regenerated by AI
  | 'material_added' // KB material added
  | 'comment'        // free-form comment

export interface EventActor {
  id: string
  name: string
  /** Optional URL to profile pic; UI shows initials as fallback. */
  avatarUrl?: string
  role: 'author' | 'reviewer' | 'admin' | 'system' | 'llm'
}

export interface EventLog {
  id: string
  bidId: string
  /** Optional chapter scope — for chapter-level events only. */
  chapterId?: string
  kind: EventKind
  /** Display label the UI can show directly without knowing each
   *  kind's metadata shape. e.g. "驳回" / "已批准" / "生成新版本". */
  label: string
  /** Subtitle / second line. Often carries the reason / summary. */
  description?: string
  actor: EventActor
  /** When the event happened (server clock when backend lands). */
  at: string // ISO 8601
  /** Kind-specific metadata — UI should switch on `kind` to interpret. */
  meta?: Record<string, unknown>
}

/** Interface implemented by mock and HTTP sources alike. */
export interface EventLogSource {
  list(bidId: string): Promise<EventLog[]>
}
